### ISSUE TITLE
GitHubOauth Problems

### ISSUE THREAD

**Issue by depasite** [tan-tan-kanarek/github-php-client#63]
Hi there
I keep getting 401 response when using 

$client = new GitHubClient();
    $client->oauth->createNewAuthorization($clientId);

Same with webApplicationFlow:

I tried Oauth manually and it works fine.
Am I missing somethings or is there a problem?

**Comment by tan-tan-kanarek** [comment]
The entire oauth service was auto-generated and never tested, I fixed it now to support the latest actions: https://github.com/tan-tan-kanarek/github-php-client/pull/64.
Please retry.

**Comment by depasite** [comment]
Hi
Thanks for the update.
Still not having any luck
Both
getAingleAuthorization
and
createNewAuthorization

Still giving me 401 back.
Caught exception: Expected status [201], actual status [401], URL [/authorizations]

**Comment by tan-tan-kanarek** [comment]
Could you please share your code?

**Comment by depasite** [comment]
Do you have skype?

**Comment by depasite** [comment]
Please add me on skype
pedri.oosthuizen
